name: medium_articles
channels:
  - pytorch
  - conda-forge
dependencies:
  - bs4=4.10.0
  - wordcloud=1.8.1
  - nltk=3.6.5
  - keybert=0.5.0
  - transformers=4.16.2
  - streamlit=1.5.1
  - matplotlib